CREATE SEQUENCE IF NOT EXISTS SQ_SALE
    START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS TB_SALE (
    id BIGINT NOT NULL DEFAULT nextval('SQ_SALE'),
    code_sale VARCHAR(50) NOT NULL,
    client_id BIGINT NOT NULL,
    sale_date TIMESTAMP WITH TIME ZONE NOT NULL,
    status_sale VARCHAR(20) NOT NULL,

    CONSTRAINT PK_SALE PRIMARY KEY (id),
    CONSTRAINT UK_CODE_SALE UNIQUE (code_sale),

    CONSTRAINT FK_SALE_CLIENT FOREIGN KEY (client_id)
        REFERENCES TB_CLIENT (id),

    CONSTRAINT CK_SALE_STATUS CHECK (
        status_sale IN ('INITIATED', 'COMPLETED', 'CANCELLED')
    )
);
