CREATE TABLE IF NOT EXISTS TB_SALE_ITEM (
    sale_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(10, 2) NOT NULL,

    CONSTRAINT PK_SALE_ITEM PRIMARY KEY (sale_id, product_id),

    CONSTRAINT FK_SALE_ITEM_SALE FOREIGN KEY (sale_id)
    REFERENCES TB_SALE (id)
    ON DELETE CASCADE,

    CONSTRAINT FK_SALE_ITEM_PRODUCT FOREIGN KEY (product_id)
    REFERENCES TB_PRODUCT (id),

    CONSTRAINT CK_SALE_ITEM_QUANTITY CHECK (quantity > 0),
    CONSTRAINT CK_SALE_ITEM_PRICE CHECK (unit_price >= 0)
    );